# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d76bb3ae1de707ddd87436bc13be67c5"
name = "kowshik2"
handle = "kowshik2"
application_url = "https://example.com/"
embedded = true

[build]
dev_store_url = "kowshik04.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
