on: [push, pull_request]

name: CI

env:
  DISABLE_V8_COMPILE_CACHE: 1

jobs:
  CI:
    name: CI_Node_${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [16, 18, 20]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - name: Install
        run: yarn install --ignore-engines
      - name: Run package tests
        run: yarn test:ci
      - name: Run linting
        run: yarn lint
